set(DEPENDENCIES_PROFILE "Everyday" CACHE STRING "How dependencies are handled: Everyday(default, assumes dependencies are available), Update (from Conan, may build if not available, updates pip and conan), CI_Everyday, CI_Update")

if(${DEPENDENCIES_PROFILE} STREQUAL "Everyday")
  message(STATUS "Ignoring dependencies")
  set(UPDATE_CONAN False)
  set(GET_DEPENDENCIES False)
  set(BUILD_MISSING_DEPENDENCIES False)
  set(IS_CI False)
elseif(${DEPENDENCIES_PROFILE} STREQUAL "Update")
  message(STATUS "Updating Pip and Conan, getting dependencies from Conan, building missing")
  set(UPDATE_CONAN True)
  set(GET_DEPENDENCIES True)
  set(BUILD_MISSING_DEPENDENCIES True)
  set(IS_CI False)
elseif(${DEPENDENCIES_PROFILE} STREQUAL "CI_Everyday")
  set(UPDATE_CONAN False)
  set(GET_DEPENDENCIES True)
  set(BUILD_MISSING_DEPENDENCIES False)
  set(IS_CI True)
elseif(${DEPENDENCIES_PROFILE} STREQUAL "CI_Update")
  set(UPDATE_CONAN False)
  set(GET_DEPENDENCIES True)
  set(BUILD_MISSING_DEPENDENCIES True)
  set(IS_CI True)
else()
  message(FATAL_ERROR "bad DEPENDENCIES_PROFILE: ${DEPENDENCIES_PROFILE} Must be one of {Everyday, Update, CI_Everyday, CI_Update}")
endif()

if(${IS_CI} AND ${IS_WINDOWS})
  set(USE_FINEGRAINED_UNIT_TESTS False)
else()
  set(USE_FINEGRAINED_UNIT_TESTS True)
endif()
